//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DInTaskScheduler.Infrastructure.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationEnvironment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationEnvironment()
        {
            this.Job = new HashSet<Job>();
        }
    
        public int Id { get; set; }
        public int IdApplication { get; set; }
        public int IdEnvironment { get; set; }
        public string EndpointUrlInfo { get; set; }
        public int IdStatus { get; set; }
        public string ApiKey { get; set; }
        public string SecretKey { get; set; }
        public string EndpointUrlBase { get; set; }
        public string UrlEndpointLogin { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Environment Environment { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Job { get; set; }
    }
}
