//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DInTaskScheduler.Infrastructure.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobParameter
    {
        public int Id { get; set; }
        public string PropertyName { get; set; }
        public int IdPropertyType { get; set; }
        public int IdJob { get; set; }
        public Nullable<int> IdSpecialFunction { get; set; }
        public int IdParameterType { get; set; }
        public Nullable<int> IdJobParameter { get; set; }
        public string Value { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual ParameterType ParameterType { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual SpecialFunction SpecialFunction { get; set; }
    }
}
